spring.application.name=spring-boot-demo
server.port=8082
rest.template.url=https://jsonmock.hackerrank.com/api/moviesdata/search/

#Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password


 #Not to let Hibernate create tables
spring.jpa.hibernate.ddl-auto=none
#to print sql queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Dialect (Spring Boot usually auto-detects)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Run schema.sql automatically
spring.sql.init.mode=always